services:
    gcs-emulator:
        image: fsouza/fake-gcs-server:latest
        volumes:
            - storage_volume:/storage
        networks:
            - internal_net
        ports:
          - 4443:4443
        command:
          - "-external-url=http://gcs-emulator:4443"
          - "-scheme=http"
          - "-port=4443"
          - "-backend=filesystem"
        

    db:
        image: postgis/postgis:17-3.5
        volumes:
            - database_volume:/var/lib/postgresql/data
        expose:
            - 5432
        networks:
            - internal_net
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend-migrator:
        build: "./backend"
        command: ["sh", "-c", "venv/bin/alembic upgrade head"]
        networks:
            - internal_net
        depends_on:
            db:
                condition: service_healthy
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            
    backend:
        build: "./backend"
        volumes: # Only to speed up testing.
            - ./backend/app:/home/app/
        command: ["sh", "-c", "cd app && ../venv/bin/uvicorn main:app_inst --reload --host 0.0.0.0 --port 8000 --proxy-headers"]
        ports:
            - 8000:8000
        networks:
            - internal_net
        depends_on:
            db:
                condition: service_healthy
            gcs-emulator:
                condition: service_started
            backend-migrator:
                condition: service_completed_successfully

        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            STORAGE_EMULATOR_HOST: http://gcs-emulator:4443
            GCP_STORAGE_BUCKET_NAME: ${GCP_STORAGE_BUCKET_NAME}
            AUTH_PASSWORD_READER: ${AUTH_PASSWORD_READER}
            AUTH_PASSWORD_ADMIN: ${AUTH_PASSWORD_ADMIN}
            AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

networks:
    internal_net:

volumes:
    database_volume:
    storage_volume:
