services:
    minios3:
        image: minio/minio
        ports:
            - 9001:9001
        volumes:
            - s3_mock_volume:/data
        command: server /data --console-address ":9001"
        networks:
            - internal_net
        expose:
            - 9000

    db:
        image: postgis/postgis:17-3.5
        volumes:
            - database_volume:/var/lib/postgresql/data
        expose:
            - 5432
        networks:
            - internal_net
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: unless-stopped

    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile

        restart: always
        ports:
            - 8080:80
        depends_on:
            - backend
        networks:
            - internal_net
        volumes: # Only to speed up testing.
            - ./frontend/dist:/home/www

    backend:
        build: "./backend"
        volumes: # Only to speed up testing.
            - ./backend/app:/home/app/
        command: ["sh", "-c", "../venv/bin/uvicorn main:app --reload --host 0.0.0.0 --port 8000 --proxy-headers"]
        expose:
            - 8000
        networks:
            - internal_net
        depends_on:
            - db
            - minios3
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
            S3_USERNAME: ${S3_USERNAME}
            S3_PASSWORD: ${S3_PASSWORD}
            S3_BUCKET: ${S3_BUCKET}
            S3_REGION: ${S3_REGION}

networks:
    internal_net:

volumes:
    database_volume:
    s3_mock_volume:
