server {
    listen 80;
    server_name localhost;
    
    resolver 127.0.0.11 valid=10s; # Docker's internal DNS resolver. Still important for stability.

    location / {
        root /home/www;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://backend:8000/;

        # Standard proxy headers to pass useful info to your FastAPI app
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
